// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Run STA/LTA detection over one channel. Returns the first pick, or null.
/// `sampling_rate` in Hz; needs > LTA_SECONDS of data.
DetectedPick? detectPick({
  required List<double> samples,
  required double samplingRate,
}) => RustLib.instance.api.crateApiDetectDetectPick(
  samples: samples,
  samplingRate: samplingRate,
);

/// STA/LTA trigger threshold the detector uses (for UI display).
double triggerOn() => RustLib.instance.api.crateApiDetectTriggerOn();

/// A detected P-wave onset.
class DetectedPick {
  /// Sample index of the onset within the supplied window.
  final BigInt index;

  /// STA/LTA ratio at the onset.
  final double staLtaRatio;

  const DetectedPick({required this.index, required this.staLtaRatio});

  @override
  int get hashCode => index.hashCode ^ staLtaRatio.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DetectedPick &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          staLtaRatio == other.staLtaRatio;
}
